(()=>{
'use strict';
const P=(window.NZGIS_PUZZLES||[]).map(x=>({slug:x[0],title:x[1],strap:x[2],rows:x[3],cols:x[4],releaseAt:x[5],answerAt:x[6],cells:x[7],across:x[8].map(y=>({n:y[0],clue:y[1],len:y[2]})),down:x[9].map(y=>({n:y[0],clue:y[1],len:y[2]}))}));
const NZ='Pacific/Auckland';
let nowMs=Date.now(), active=null, letters=null, reveal=false, autoOpened=false;
const $=s=>document.querySelector(s);
const els={todayTitle:$('#today-title'),todayStrap:$('#today-strap'),todayDate:$('#today-date'),todayLabel:$('#today-label'),openToday:$('#open-today'),todayAnswer:$('#today-answer'),status:$('#status-note'),next:$('#next-release'),stage:$('#puzzle-stage'),grid:$('#crossword'),pt:$('#puzzle-title'),ps:$('#puzzle-strap'),pr:$('#puzzle-release'),ac:$('#across'),dn:$('#down'),answerBtn:$('#answer-btn'),answerPanel:$('#answer-panel'),answerList:$('#answer-list'),archive:$('#archive-grid'),search:$('#archive-search')};
const fmtDate=iso=>new Intl.DateTimeFormat('en-NZ',{timeZone:NZ,weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(iso));
const fmtShort=iso=>new Intl.DateTimeFormat('en-NZ',{timeZone:NZ,day:'numeric',month:'short',year:'numeric'}).format(new Date(iso));
const released=p=>Date.parse(p.releaseAt)<=nowMs;
const unlocked=p=>Date.parse(p.answerAt)<=nowMs;
function latest(){return P.filter(released).sort((a,b)=>Date.parse(b.releaseAt)-Date.parse(a.releaseAt))[0]||null}
function nextPuzzle(){return P.filter(p=>!released(p)).sort((a,b)=>Date.parse(a.releaseAt)-Date.parse(b.releaseAt))[0]||null}
function nzDate(ms){return new Intl.DateTimeFormat('en-CA',{timeZone:NZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ms))}
function miniGrid(p){const g=$('#mini-grid');g.innerHTML='';const occupied=new Set(p.cells.map(c=>`${c[0]},${c[1]}`));let minR=Math.min(...p.cells.map(c=>c[0])),maxR=Math.max(...p.cells.map(c=>c[0])),minC=Math.min(...p.cells.map(c=>c[1])),maxC=Math.max(...p.cells.map(c=>c[1]));for(let r=minR;r<=Math.min(maxR,minR+6);r++)for(let c=minC;c<=Math.min(maxC,minC+6);c++){const s=document.createElement('span');if(!occupied.has(`${r},${c}`))s.className='off';g.appendChild(s)}}
function renderHome(){const cur=latest();if(!cur){els.todayTitle.textContent='First crossword coming soon';els.todayStrap.textContent='The first weekday puzzle will appear here at 9:00 am New Zealand time.';els.openToday.disabled=true;return}const isToday=nzDate(Date.parse(cur.releaseAt))===nzDate(nowMs);els.todayLabel.textContent=isToday?'Today’s crossword':'Latest crossword';els.todayTitle.textContent=cur.title;els.todayStrap.textContent=cur.strap;els.todayDate.textContent=fmtDate(cur.releaseAt);els.openToday.disabled=false;els.openToday.onclick=()=>openPuzzle(cur.slug,true);els.todayAnswer.textContent=unlocked(cur)?'Answers available':'Answers unlock at 2 pm';els.todayAnswer.disabled=!unlocked(cur);els.todayAnswer.onclick=()=>openPuzzle(cur.slug,true,true);els.status.textContent=unlocked(cur)?'Answers are available, but remain hidden until you choose to reveal them.':'Today’s answers are locked until 2:00 pm New Zealand time.';miniGrid(cur);const nx=nextPuzzle();els.next.textContent=nx?`Next crossword: ${fmtDate(nx.releaseAt)} at 9:00 am NZ time.`:'The current release queue is complete.';renderArchive(cur)}
function renderArchive(cur){const q=(els.search.value||'').trim().toLowerCase();const list=P.filter(p=>released(p)&&(!cur||p.slug!==cur.slug)).sort((a,b)=>Date.parse(b.releaseAt)-Date.parse(a.releaseAt)).filter(p=>!q||`${p.title} ${p.strap}`.toLowerCase().includes(q));els.archive.innerHTML=list.map(p=>`<a class="archive-card" href="?p=${encodeURIComponent(p.slug)}" data-slug="${p.slug}"><div class="archive-date">${fmtShort(p.releaseAt)}</div><h3>${p.title}</h3><p>${p.strap}</p><div class="archive-meta">Open puzzle · answers stay hidden</div></a>`).join('');els.archive.querySelectorAll('[data-slug]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openPuzzle(a.dataset.slug,true)}))}
function buildGrid(p){const occupied=new Map(p.cells.map(c=>[`${c[0]},${c[1]}`,c[2]]));els.grid.style.gridTemplateColumns=`repeat(${p.cols},1fr)`;els.grid.innerHTML='';for(let r=0;r<p.rows;r++)for(let c=0;c<p.cols;c++){const k=`${r},${c}`,cell=document.createElement('div');if(!occupied.has(k)){cell.className='cell off'}else{cell.className='cell';const n=occupied.get(k);cell.innerHTML=(n?`<span class="num">${n}</span>`:'')+`<span class="letter" data-cell="${k}"></span>`}els.grid.appendChild(cell)}}
function clueHTML(items){return items.sort((a,b)=>a.n-b.n).map(x=>`<li><b>${x.n}</b><span>${x.clue} <small>(${x.len})</small></span></li>`).join('')}
async function openPuzzle(slug,scroll=true,wantAnswers=false){const p=P.find(x=>x.slug===slug);if(!p||!released(p))return;active=p;letters=null;reveal=false;els.pt.textContent=p.title;els.ps.textContent=p.strap;els.pr.textContent=fmtDate(p.releaseAt);els.ac.innerHTML=clueHTML([...p.across]);els.dn.innerHTML=clueHTML([...p.down]);els.answerPanel.classList.remove('show');els.answerList.innerHTML='';buildGrid(p);els.answerBtn.disabled=!unlocked(p);els.answerBtn.textContent=unlocked(p)?'Reveal answers':'Answers unlock at 2 pm';els.answerBtn.onclick=toggleAnswers;els.stage.classList.add('show');history.replaceState(null,'',`?p=${encodeURIComponent(slug)}`);if(scroll)els.stage.scrollIntoView({behavior:'smooth',block:'start'});if(wantAnswers&&unlocked(p))await toggleAnswers()}
async function toggleAnswers(){if(!active||!unlocked(active))return;if(reveal){document.querySelectorAll('[data-cell]').forEach(el=>el.textContent='');reveal=false;els.answerBtn.textContent='Reveal answers';els.answerPanel.classList.remove('show');return}if(!letters){els.answerBtn.disabled=true;els.answerBtn.textContent='Loading answers…';try{const r=await fetch(`/api/answers?slug=${encodeURIComponent(active.slug)}`,{cache:'no-store'});if(r.status===423){nowMs=Date.now();els.answerBtn.textContent='Answers unlock at 2 pm';return}if(!r.ok)throw new Error('answer request failed');const j=await r.json();letters={};active.cells.forEach((c,i)=>letters[`${c[0]},${c[1]}`]=j.letters.charAt(i));els.answerList.innerHTML=j.answers.sort((a,b)=>a[0]-b[0]||a[1].localeCompare(b[1])).map(a=>`<span>${a[0]}${a[1]} ${a[2]}</span>`).join('')}catch(e){els.answerBtn.textContent='Try answers again';els.status.textContent='The answer service could not be reached. The puzzle itself is still available.';return}finally{els.answerBtn.disabled=false}}document.querySelectorAll('[data-cell]').forEach(el=>el.textContent=letters[el.dataset.cell]||'');reveal=true;els.answerBtn.textContent='Hide answers';els.answerPanel.classList.add('show')}
function closePuzzle(){els.stage.classList.remove('show');history.replaceState(null,'',location.pathname);window.scrollTo({top:document.querySelector('.main').offsetTop,behavior:'smooth'})}
function printPuzzle(){if(!active)return;window.print()}
async function syncTime(){try{const r=await fetch('/api/status',{cache:'no-store'});if(r.ok){const j=await r.json();if(Number.isFinite(j.now))nowMs=j.now;else nowMs=Date.now()}else nowMs=Date.now()}catch(e){nowMs=Date.now()}renderHome();if(active){const wasLocked=els.answerBtn.disabled;if(unlocked(active)&&wasLocked){els.answerBtn.disabled=false;els.answerBtn.textContent='Reveal answers'}}}
els.search.addEventListener('input',()=>renderArchive(latest()));$('#close-puzzle').onclick=closePuzzle;$('#print-puzzle').onclick=printPuzzle;
syncTime().then(()=>{const requested=new URLSearchParams(location.search).get('p');if(requested){const p=P.find(x=>x.slug===requested);if(p&&released(p))openPuzzle(requested,false)}autoOpened=true});setInterval(syncTime,60000);
})();